import type { Metadata } from "next";
import "./globals.css";
import { roboto_slab } from "./ui/font";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={`${roboto_slab.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
